name: Preveri PDF

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lunarstarlight/fmfdelo-texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Preveri PDFje
        run : |
          cd src
          echo "Compiling src"

          basename="main"
          texname=$basename.tex
          pdfname=$basename.pdf

          latexmk -pdflua $texname
          verapdf -f 2b $pdfname

